### ISSUE TITLE
Error using the module

### ISSUE THREAD

**Issue by Ibrahimous** [franciscoescher/goopenai#6]
Hi,
Using your code with a different content, I get:
```
# API_KEY=<KEY> API_ORG=1234 go run main.go 
# github.com/franciscoescher/goopenai
/root/go/pkg/mod/github.com/franciscoescher/goopenai@v0.4.0/client.go:31:62: error: use of undefined type ‘any’
   31 | func (c *Client) Post(ctx context.Context, url string, input any) (response []byte, err error) {
      |                                                              ^
/root/go/pkg/mod/github.com/franciscoescher/goopenai@v0.4.0/client.go:31:62: error: use of undefined type ‘any’
```

**Comment by franciscoescher** [comment]
If your go doesn't recognize any, you are prob using an old go version, try updating to a version that is >= 1.18

**Comment by Ibrahimous** [comment]
Thanks a lot for your lightning-fast answer, I'm indeed on WSL Ubuntu with go 1.16, I'll upgrade right away
________________________________
De : Francisco Escher Guimarães da Silva ***@***.***>
Envoyé : vendredi 5 mai 2023 15:59
À : franciscoescher/goopenai ***@***.***>
Cc : Ibrahimous ***@***.***>; Author ***@***.***>
Objet : Re: [franciscoescher/goopenai] Error using the module (Issue #6)


If your go doesn't recognize any, you are prob using an old version, try updating to a version that is >= 1.18
